version: "3"

services:
  server:
    build:
      context: .docker/php/8.1-apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"


